name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered?
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Related package
      description: Which package is this related to?
      options:
        - berlioz/core
        - berlioz/config
        - berlioz/service-container
        - berlioz/event-manager
        - berlioz/router
        - berlioz/http-core
        - berlioz/http-message
        - berlioz/http-client
        - berlioz/cli-core
        - berlioz/mailer
        - berlioz/form
        - berlioz/flash-bag
        - berlioz/html-selector
        - berlioz/queue-manager
        - berlioz/twig-package
        - berlioz/hector-package
        - berlioz/queue-manager-package
        - Other / Not sure
    validations:
      required: false
