name: Tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request: ~
  schedule:
    - cron: '0 0 * * *'

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.2', '8.3', '8.4', '8.5' ]
        stability: [ 'prefer-lowest', 'prefer-stable' ]

    name: PHPUnit on PHP ${{ matrix.php-versions }} - ${{ matrix.stability }}

    continue-on-error: ${{ matrix.stability != 'prefer-stable' }}

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Setup PHP'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: fileinfo, intl, mbstring, xml, pdo, pdo-mysql, yaml, amqp, redis
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug

      - name: 'Install dependencies'
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: 'Execute tests'
        run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
